# Generated by Django 4.0.3 on 2023-05-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_purchase_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='vendor',
        ),
    ]
