# Generated by Django 4.0.3 on 2023-05-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_purchase_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
