# Generated by Django 4.0.3 on 2023-05-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_address',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_mobile',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
