# Generated by Django 4.0.3 on 2023-05-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': '6. Inventory'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '3. Products'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': '4. Purchases'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name_plural': '5. Sales'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name_plural': '2. Units'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name_plural': '1. Vendors'},
        ),
    ]
