# Generated by Django 4.0.3 on 2023-05-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_inventory_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': '4.Purchases'},
        ),
    ]
