# Generated by Django 4.0.3 on 2023-05-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_inventory_pur_qty_alter_inventory_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_amt',
            field=models.FloatField(editable=False),
        ),
    ]
