# Generated by Django 3.2.4 on 2023-06-29 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20230629_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='vendor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vendor'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchase',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.purchase'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sale',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='main.vendor'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amt',
            field=models.FloatField(),
        ),
    ]
