# Generated by Django 3.2.4 on 2023-06-30 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20230629_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sale',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='pur_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sale_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='vendor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vendor'),
        ),
    ]
