# Generated by Django 3.2.4 on 2023-06-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_purchase_total_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='total_bal_qty',
            field=models.FloatField(default=0),
        ),
    ]
