# Generated by Django 3.2.4 on 2023-06-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_saleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='total_amt',
            field=models.FloatField(default=0),
        ),
    ]
