# Generated by Django 3.2.4 on 2023-06-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20230630_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_amt',
            field=models.FloatField(default=0),
        ),
    ]
