# Generated by Django 3.2.4 on 2023-06-30 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_sale_total_amt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name_plural': 'Sales'},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_amt',
        ),
        migrations.AddField(
            model_name='sale',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.vendor'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.sale'),
        ),
    ]
