# Generated by Django 3.2.4 on 2023-06-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20230701_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='billed',
            field=models.BooleanField(default=False),
        ),
    ]
