# Generated by Django 4.2.2 on 2023-07-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_saleitem_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
