# Generated by Django 4.2.2 on 2023-08-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_saleitem_total_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='total_amt',
            field=models.FloatField(default=0),
        ),
    ]
