# Generated by Django 4.1.2 on 2023-08-08 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_sale_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_purchases', to='main.vendor'),
        ),
    ]
