# Generated by Django 4.1.2 on 2023-08-08 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_purchase_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory', to='main.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='vendor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_inventory', to='main.vendor'),
        ),
    ]
